# Site
name: "CIPHERLEAKs"
title: "CIPHERLEAKs: Ciphertext Side Channels on AMD SEV"
description: "Cipherleaks is the first demonstrated attack against AMD SEV-SNP. It exploits a vulnerable design feature of SEV's memory encryption and uses the ciphertext of the encrypted VM Save Area (VMSA) as side channels to breach constant-time RSA and ECDSA implementation of the latest OpenSSL library."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
# google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: li.7533@osu.edu
theme: jekyll-uikit

# Authors
authors:
  mengyuan:
    name: Mengyuan
    display_name: Mengyuan
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: li.7533@osu.edu
    # web: https://www.wowthemes.net
    # twitter: https://twitter.com/wowthemesnet
    description: "Ph.D. student in The Ohio State University."

# Plugins
plugins:
  - github-pages
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-algolia

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
port: 1234    
# Pagination 
# paginate: 6
# paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [vendor, changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
